on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: [self-hosted, linux, x64, test_amplify]

    steps:
      - name: Checkout code to sandboxed path
        uses: actions/checkout@v4
        with:
          path: repo

      - name: Copy code to /app/DATA
        run: |
          sudo rm -rf /home/ubuntu/actioncheck/DATA/*
          sudo cp -r repo/* /home/ubuntu/actioncheck/DATA
